name: smoking_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # Utility
  cupertino_icons: ^1.0.2

  # State Management
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7
  mobx_codegen: ^2.0.7

  # Localization
  easy_localization: ^3.0.0

  # Google
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  
  # Cache
  shared_preferences: ^2.0.15
  provider: ^6.0.3

  # Test
  device_preview: ^1.1.0
  auto_size_text: ^3.0.0
  percent_indicator: ^4.2.2
  
  # Animation
  lottie: ^2.3.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # Google
  build_runner: ^2.2.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/lottie/

